Changes to support Sync replication
dell/gopowerstore pull request #132
Opened 2024-09-13 06:32 UTC by rajendraindukuri

# PR Submission checklist

# GitHub Issues
| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1443 |

# Common PR Checklist:

- [ ] Have you made sure that the code compiles?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Have you maintained backward compatibility

## Description of your changes:
- Added Zero to the list of RPOEnum values
- Added unit tests for RPOEnum and CreateReplicationRule use case to reflect sync replication

## Unit test results:
![image](https://github.com/user-attachments/assets/44fe3d10-e66e-4ee6-a41e-416a90203011)

![image](https://github.com/user-attachments/assets/a9ecc9e1-9538-4588-90a0-610f856cb876)

2024-09-13 13:13 UTC, lukeatdell requested changes
Please also update or add integration tests under /inttests to test the changes.

2024-09-13 14:28 UTC, santhoshatdell approved these changes
Please address Luke's comment.

2024-09-13 14:28 UTC, santhoshatdell commented on replication_test.go
>  }
Copyright year needs update.

2024-09-16 13:16 UTC, rajendraindukuri commented on replication_test.go
>  }
done

2024-09-16 13:17 UTC, rajendraindukuri commented on replication_types.go
> +	// If RPO is Zero, it indicates the replication_type is 'sync'.
done

2024-09-16 13:19 UTC, rajendraindukuri commented
@lukeatdell Added int tests for Sync Replication until volume group creation. This can be enhanced to add Replication session related tests post the changes are implemented. Thanks.

2024-09-16 13:20 UTC, rajendraindukuri commented
> Please address Luke's comment.

Done

2024-09-16 13:32 UTC, AkshaySainiDell requested changes

2024-09-16 13:32 UTC, AkshaySainiDell commented on inttests/replication_sync_test.go
> + * Copyright © 2021-2024 Dell Inc. or its subsidiaries. All Rights Reserved.
```suggestion
 * Copyright © 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
```

2024-09-16 13:32 UTC, AkshaySainiDell commented on replication_types_test.go
> + * Copyright © 2021-2024 Dell Inc. or its subsidiaries. All Rights Reserved.
```suggestion
 * Copyright © 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
```

2024-09-16 13:36 UTC, lukeatdell submitted a review, later dismissed
Thanks for adding the tests!

2024-09-17 04:40 UTC, AkshaySainiDell approved these changes

2024-09-17 04:42 UTC, HarishH-DELL approved these changes

2024-09-17 04:59 UTC, merged