added apis for snapshot_rule required for terraform plugins
dell/gopowerstore pull request #90
Opened 2022-10-27 08:15 UTC by mkmayank-dell

# PR Submission checklist

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Common PR Checklist:

- [ ] Have you made sure that the code compiles?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Have you maintained backward compatibility

## Description of your changes:
Implemented following APIs
GET /snapshot_rule 
POST /snapshot_rule
GET
 ​/snapshot_rule​/{id}
DELETE /snapshot_rule​/{id}

Ran unit tests and integration tests
Also, tried the example code to do changes to powerstore instance using the above implemented APIs

2022-11-08 12:53 UTC, mkmayank-dell commented
![image](https://user-images.githubusercontent.com/116156726/200569126-3e9b510f-654c-4b55-9cb2-679be671bfb6.png)


New file snapshot_rule.go and snapshot_rule_types.go added with 100% UT coverage .

Overall coverage remains the same.

![image](https://user-images.githubusercontent.com/116156726/200569653-bcf228f8-ed2f-4fd6-8585-36ccfab02038.png)

2022-11-11 05:04 UTC, AkshaySainiDell approved these changes

2022-11-11 06:28 UTC, AkshaySainiDell requested changes
Copyright info must to be added to all the files.

2022-11-11 06:53 UTC, AkshaySainiDell approved these changes

2022-11-11 18:42 UTC, Sakshi-dell approved these changes

2022-11-11 18:48 UTC, merged